server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.196.32.68:3306/trade?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: ningbo.com
  mail:
    # QQ邮箱发送邮件服务器
    host: smtp.qq.com
    # 发送者的邮箱授权码，开启IMAP/SMTP服务时会生成
    password: lyxrmiykgyeibdde
    # 协议
    protocol: smtp
    # 发送者的邮箱账号
    username: 1071781349@qq.com
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:com.example.demo.mapper/*.xml

system:
  swagger:
    enable: true
    host: localhost:${server.port}

