server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://139.196.32.68:3306/trade?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: ningbo.com

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml

system:
  swagger:
    enable: true
    host: localhost:${server.port}

